"""The three programmatic ``run_*`` entry points and their pipeline helpers.

Each ``run_*`` function drives a full subcommand pipeline: bundle-root and
pattern validation (R-CLI-010..R-CLI-011, R-FS-001..R-FS-004), config-chain
loading (R-CFG-051), schema-type resolution, per-label scraping with
fail-slow accumulation (R-FSLOW-110), and atomic output writing (R-ERR-002).
The functions raise :class:`~pds4indextools.errors.Pds4IndexError` subclasses
on failure (R-API-004); the CLI dispatcher maps those to exit codes.

Implements spec section 4 (R-IDX-*), section 5, section 6, section 17.3
(R-FSLOW-*), and section 20 (R-API-*).
"""

import importlib.resources
from collections.abc import Iterator, Mapping, Sequence
from contextlib import contextmanager
from pathlib import Path

from lxml import etree

from pds4indextools._io import _atomic_writes
from pds4indextools._logging import module_logger
from pds4indextools.cli._args import (
    CopyDefaultConfigArgs,
    CopyDefaultConfigResult,
    GenerateIndexFileArgs,
    GenerateIndexFileResult,
    GenerateXpathListArgs,
    GenerateXpathListResult,
)
from pds4indextools.cli._paths import (
    _resolve_output_paths,
    _resolve_xpath_list_output_path,
)
from pds4indextools.config import ColumnSpec, IndexConfig, load_config
from pds4indextools.csv_writer import CsvWritePlan, build_plan, write_csv
from pds4indextools.errors import (
    CliError,
    ConfigError,
    FailSlowAggregateError,
    OutputError,
    ParseError,
    Pds4IndexError,
)
from pds4indextools.label_writer import (
    build_substitution_dict,
    load_packaged_template,
    write_label,
)
from pds4indextools.schema_types import SchemaCache, SchemaTypeResolver
from pds4indextools.scraper import ScrapeResult, scrape_label

__all__ = [
    'run_copy_default_config',
    'run_generate_index_file',
    'run_generate_xpath_list',
]

_logger = module_logger('cli')

# The three bytes an encoder emits for a UTF-8 byte-order mark (R-PARSE-001).
_UTF8_BOM = b'\xef\xbb\xbf'

_XPATH_LIST_PREAMBLE = (
    '# Generated by pds4_create_xml_index generate_xpath_list.\n'
    '# Edit each `name:` (or delete unwanted entries), then merge this\n'
    '# `columns:` block into one of your --config-file YAMLs.\n'
    'columns:\n'
)


def _emit_warnings(warnings: Sequence[str]) -> None:
    """Log each output-path warning at WARNING level (R-OUT-013)."""
    for warning in warnings:
        _logger.warning('%s', warning)


def _resolve_bundle_root(bundle_root: Path) -> Path:
    """Resolve ``bundle_root`` to an absolute directory (R-FS-001).

    Parameters:
        bundle_root: The requested bundle root, possibly relative or a symlink.

    Returns:
        The resolved absolute :class:`~pathlib.Path`.

    Raises:
        CliError: If the resolved path is not a directory (R-CLI-010).
    """
    resolved = bundle_root.resolve()
    if not resolved.is_dir():
        raise CliError(f'bundle root is not a directory: {resolved}', file_path=resolved)
    return resolved


def _discover_labels(bundle_root: Path, patterns: Sequence[str]) -> list[Path]:
    """Discover, deduplicate, and ``filespec``-sort the matching label files.

    Parameters:
        bundle_root: The resolved absolute bundle root.
        patterns: The relative glob patterns to union.

    Returns:
        The matching label paths, deduplicated by resolved path and sorted by
        ``filespec`` (R-DISC-020, R-FS-004).

    Raises:
        CliError: If any pattern is absolute (R-CLI-011) or the union is empty
            (R-DISC-010).
    """
    matched: dict[Path, Path] = {}
    for pattern in patterns:
        if Path(pattern).is_absolute():
            raise CliError(f'glob pattern must be relative to --bundle-root: {pattern!r}')
        for path in bundle_root.glob(pattern):
            matched.setdefault(path.resolve(), path)
    if not matched:
        raise CliError(
            f'no files matched any of the patterns {list(patterns)!r} under {bundle_root}'
        )
    return sorted(matched.values(), key=lambda p: p.resolve().relative_to(bundle_root).as_posix())


def _load_validated_config(config_files: Sequence[Path]) -> IndexConfig:
    """Resolve and load the config chain into a validated :class:`IndexConfig`.

    Parameters:
        config_files: The user config paths, in increasing priority order.

    Returns:
        The validated merged configuration (R-CFG-051, R-CFG-052).
    """
    resolved = tuple(path.resolve() for path in config_files)
    return load_config(resolved)


def _leaf_tag(xpath: str) -> str:
    """Return the prefixed leaf tag of a canonical XPath, without a predicate."""
    return xpath.rsplit('/', 1)[-1].split('<', 1)[0]


def _register_label_schemas(resolver: SchemaTypeResolver, label_path: Path) -> None:
    """Parse ``label_path`` and register its declared schemas on ``resolver``.

    Registration must precede scraping so nilled-element type resolution and
    cross-label version consistency (R-SCH-040) see every label's schemas.

    The UTF-8 BOM is rejected here, before parsing, so a BOM label fails
    identically to and no later than the scraper's own BOM check would: lxml
    accepts a BOM, so parsing first would bind the label's namespaces into the
    shared resolver before the scraper rejected it, and under ``--fail-slow``
    those stale bindings could provoke a spurious cross-label
    ``SchemaVersionError`` (R-SCH-040) against a later label (#60).

    Parameters:
        resolver: The per-run schema-type resolver.
        label_path: The label file to register.

    Raises:
        ParseError: If the label begins with a UTF-8 BOM (R-PARSE-001) or is not
            well-formed XML (R-PARSE-002).
        SchemaError: Propagated from
            :meth:`~pds4indextools.schema_types.SchemaTypeResolver.register_label`.
    """
    with label_path.open('rb') as handle:
        if handle.read(3) == _UTF8_BOM:
            raise ParseError('UTF-8 BOM not permitted', file_path=label_path)
    try:
        tree = etree.parse(str(label_path))
    except etree.XMLSyntaxError as exc:
        raise ParseError(f'failed to parse label: {exc}', file_path=label_path) from exc
    resolver.register_label(label_path, tree.getroot())


def _scrape_all(
    bundle_root: Path,
    labels: Sequence[Path],
    *,
    config: IndexConfig,
    resolver: SchemaTypeResolver,
    fail_slow: bool,
) -> list[ScrapeResult]:
    """Register and scrape every label, honoring fail-slow accumulation.

    Parameters:
        bundle_root: The resolved absolute bundle root.
        labels: The discovered label files, in ``filespec`` order.
        config: The validated configuration supplying nillable/output settings.
        resolver: The per-run schema-type resolver.
        fail_slow: ``True`` accumulates fail-slow-eligible errors and raises a
            single :class:`~pds4indextools.errors.FailSlowAggregateError` after
            processing every label (R-FSLOW-110, R-FSLOW-120).

    Returns:
        The successful scrape results, in discovery order.

    Raises:
        Pds4IndexError: The first error when not fail-slow, or a non-eligible
            error even under fail-slow.
        FailSlowAggregateError: When fail-slow accumulated at least one error.
    """
    seen_lids: dict[str, Path] = {}
    results: list[ScrapeResult] = []
    errors: list[Pds4IndexError] = []
    for label_path in labels:
        try:
            _register_label_schemas(resolver, label_path)
            results.append(
                scrape_label(
                    label_path,
                    bundle_root=bundle_root,
                    resolver=resolver,
                    nillable_config=config.nillable,
                    fixed_width_mode=config.output.fixed_width,
                    seen_lids=seen_lids,
                )
            )
        except Pds4IndexError as exc:
            if fail_slow and exc.FAIL_SLOW_ELIGIBLE:
                _logger.warning('%s', exc)
                errors.append(exc)
            else:
                raise
    if fail_slow and errors:
        raise FailSlowAggregateError(errors)
    return results


def _project_rows(
    results: Sequence[ScrapeResult], columns: Sequence[ColumnSpec]
) -> list[dict[str, str]]:
    """Project each scrape result onto the configured columns (R-MAP-310/311).

    Parameters:
        results: The successful scrape results.
        columns: The configured output columns.

    Returns:
        One row dict per result, keyed by column header; an XPath column
        matching no label yields an empty cell (R-MAP-311).
    """
    rows: list[dict[str, str]] = []
    for result in results:
        row: dict[str, str] = {}
        for column in columns:
            token = column.auto
            if token is not None:
                row[column.header] = result.auto_columns[token]
            else:
                row[column.header] = result.rows.get(column.selector, '')
        rows.append(row)
    return rows


def _build_column_metadata(
    columns: Sequence[ColumnSpec], resolver: SchemaTypeResolver
) -> tuple[list[str], dict[str, bool], dict[str, str], dict[str, str], dict[str, str]]:
    """Assemble the parallel per-column metadata the writers need.

    Parameters:
        columns: The configured output columns.
        resolver: The per-run schema-type resolver used to type XPath columns.

    Returns:
        A ``(headers, column_is_auto, auto_tokens, column_xpaths,
        column_types)`` tuple. ``auto_tokens`` omits XPath columns; the other
        maps are keyed by every column header.

    Raises:
        SchemaResolutionError: If an XPath column's leaf tag cannot be typed.
    """
    headers = [column.header for column in columns]
    column_is_auto = {column.header: column.auto is not None for column in columns}
    auto_tokens = {column.header: column.auto for column in columns if column.auto is not None}
    column_xpaths = {column.header: column.selector for column in columns}
    column_types: dict[str, str] = {}
    for column in columns:
        token = column.auto
        if token is not None:
            column_types[column.header] = resolver.auto_column_type(token)
        else:
            column_types[column.header] = resolver.resolve(_leaf_tag(column.selector))
    return headers, column_is_auto, auto_tokens, column_xpaths, column_types


@contextmanager
def _template_source(label_template: Path | None) -> Iterator[Path]:
    """Yield the label template path, packaged default or user-supplied.

    Parameters:
        label_template: The custom template path, or ``None`` for the packaged
            default (R-LBL-001, R-LBL-002).

    Yields:
        The template file :class:`~pathlib.Path`.
    """
    if label_template is not None:
        yield label_template
    else:
        with load_packaged_template() as path:
            yield path


def _write_index_outputs(
    plan: CsvWritePlan,
    csv_path: Path,
    label_path: Path,
    *,
    args: GenerateIndexFileArgs,
    config: IndexConfig,
    columns: Sequence[ColumnSpec],
    column_types: Mapping[str, str],
    column_xpaths: Mapping[str, str],
) -> None:
    """Write the CSV and label atomically, cleaning up on any failure.

    The CSV is written to its final path first so the label's
    ``$FILE_ZULU``/``$FILE_MD5`` macros stat the real file; the label is
    written to a temporary sibling and renamed on success. Any failure after
    the CSV is written removes it too, so an interrupted run leaves neither a
    partial nor a stale output (R-ERR-002).

    Parameters:
        plan: The CSV write plan.
        csv_path: The absolute final CSV path.
        label_path: The absolute final label path.
        args: The originating argument bundle (for the post-write hook and
            template).
        config: The validated configuration (label contents, line ending).
        columns: The configured output columns, parallel to ``plan.columns``.
        column_types: Maps each header to its resolved PDS4 type.
        column_xpaths: Maps each header to its raw XPath or auto token.
    """
    label_tmp = label_path.with_name(label_path.name + '.tmp')
    with _atomic_writes((label_tmp, label_path)):
        write_csv(plan, csv_path)
        try:
            if args.csv_post_write_hook is not None:
                args.csv_post_write_hook(csv_path)
            substitution = build_substitution_dict(
                label_contents=config.label_contents,
                plan=plan,
                column_specs=columns,
                column_types=column_types,
                column_xpaths=column_xpaths,
                csv_absolute_path=csv_path,
            )
            with _template_source(args.label_template) as template_path:
                write_label(
                    template_path,
                    substitution,
                    label_tmp,
                    line_ending=config.output.line_ending,
                )
        except BaseException:
            csv_path.unlink(missing_ok=True)
            raise


def run_generate_index_file(args: GenerateIndexFileArgs) -> GenerateIndexFileResult:
    """Scrape a bundle and write an index CSV plus its PDS4 label.

    Parameters:
        args: The argument bundle mirroring the ``generate_index_file`` CLI.

    Returns:
        The :class:`GenerateIndexFileResult` describing the written outputs.

    Raises:
        CliError: On an invalid bundle root, pattern, or empty discovery.
        ConfigError: On an invalid config chain or a config with no columns.
        Pds4IndexError: On a scraping, schema, or output failure.
        FailSlowAggregateError: When fail-slow accumulated errors (R-API-004).

    The ``args.verbosity`` field is advisory for programmatic callers: logging
    configuration is the CLI's responsibility (:func:`main`), so this function
    does not reconfigure logging from it.

    Implements spec section 4 and R-API-003.
    """
    bundle_root = _resolve_bundle_root(args.bundle_root)
    labels = _discover_labels(bundle_root, args.patterns)
    config = _load_validated_config(args.config_files)
    if config.columns is None:
        raise ConfigError(
            'no columns defined in config; run generate_xpath_list to produce '
            'a starter columns block'
        )
    columns = config.columns
    resolver = SchemaTypeResolver(SchemaCache(cache_dir=config.xsd_cache_dir))
    csv_path, label_path, warnings = _resolve_output_paths(args.output_file)
    _emit_warnings(warnings)
    results = _scrape_all(
        bundle_root, labels, config=config, resolver=resolver, fail_slow=args.fail_slow
    )
    rows = _project_rows(results, columns)
    headers, column_is_auto, auto_tokens, column_xpaths, column_types = _build_column_metadata(
        columns, resolver
    )
    plan = build_plan(
        rows=rows,
        columns=headers,
        column_is_auto=column_is_auto,
        auto_tokens=auto_tokens,
        output_section=config.output,
    )
    _write_index_outputs(
        plan,
        csv_path,
        label_path,
        args=args,
        config=config,
        columns=columns,
        column_types=column_types,
        column_xpaths=column_xpaths,
    )
    return GenerateIndexFileResult(
        csv_path=csv_path,
        label_path=label_path,
        rows_written=len(rows),
        columns_written=len(columns),
        warnings=warnings,
    )


def _aggregate_xpaths(results: Sequence[ScrapeResult]) -> tuple[str, ...]:
    """Union every scraped canonical XPath, preserving first-occurrence order."""
    ordered: dict[str, None] = {}
    for result in results:
        for xpath in result.rows:
            ordered.setdefault(xpath, None)
    return tuple(ordered)


def _write_xpath_list(output_path: Path, xpaths: Sequence[str]) -> None:
    """Write the ``columns:`` YAML block for the observed XPaths, atomically.

    Parameters:
        output_path: The absolute YAML output path.
        xpaths: The canonical XPaths in first-occurrence order.
    """
    parts = [_XPATH_LIST_PREAMBLE]
    for xpath in xpaths:
        parts.append(f'  - xpath: {xpath}\n    name: {xpath}\n')
    temp_path = output_path.with_name(output_path.name + '.tmp')
    with _atomic_writes((temp_path, output_path)):
        temp_path.write_bytes(''.join(parts).encode('utf-8'))


def run_generate_xpath_list(args: GenerateXpathListArgs) -> GenerateXpathListResult:
    """Scrape a bundle and write a starter ``columns:`` YAML block.

    Parameters:
        args: The argument bundle mirroring the ``generate_xpath_list`` CLI.

    Returns:
        The :class:`GenerateXpathListResult` describing the written YAML.

    Raises:
        CliError: On an invalid bundle root, pattern, or empty discovery.
        ConfigError: On an invalid config chain.
        Pds4IndexError: On a scraping or schema failure.
        FailSlowAggregateError: When fail-slow accumulated errors (R-API-004).

    The ``args.verbosity`` field is advisory for programmatic callers: logging
    configuration is the CLI's responsibility (:func:`main`), so this function
    does not reconfigure logging from it.

    Implements spec section 5 and R-API-003.
    """
    bundle_root = _resolve_bundle_root(args.bundle_root)
    labels = _discover_labels(bundle_root, args.patterns)
    config = _load_validated_config(args.config_files)
    resolver = SchemaTypeResolver(SchemaCache(cache_dir=config.xsd_cache_dir))
    output_path, warnings = _resolve_xpath_list_output_path(args.output_file)
    _emit_warnings(warnings)
    results = _scrape_all(
        bundle_root, labels, config=config, resolver=resolver, fail_slow=args.fail_slow
    )
    xpaths = _aggregate_xpaths(results)
    _write_xpath_list(output_path, xpaths)
    return GenerateXpathListResult(
        output_path=output_path, xpath_count=len(xpaths), warnings=warnings
    )


def run_copy_default_config(args: CopyDefaultConfigArgs) -> CopyDefaultConfigResult:
    """Write a verbatim copy of the packaged default configuration.

    Parameters:
        args: The argument bundle mirroring the ``copy_default_config`` CLI.

    Returns:
        The :class:`CopyDefaultConfigResult` describing the written file.

    Raises:
        CliError: If the destination exists and ``force`` is not set (R-CLI-031).
        OutputError: If writing the destination fails.

    The ``args.verbosity`` field is advisory for programmatic callers: logging
    configuration is the CLI's responsibility (:func:`main`), so this function
    does not reconfigure logging from it.

    Implements spec section 6 and R-API-003.
    """
    data = (
        importlib.resources.files('pds4indextools.templates')
        .joinpath('default_config.yaml')
        .read_bytes()
    )
    dest = args.output_file
    if dest.exists() and not args.force:
        raise CliError('destination exists; pass --force to overwrite', file_path=dest)
    warnings: tuple[str, ...] = ()
    if dest.exists():
        message = f'overwriting existing config: {dest.resolve()}'
        _logger.warning('%s', message)
        warnings = (message,)
    try:
        dest.write_bytes(data)
    except OSError as exc:
        raise OutputError(f'failed to write config: {dest}: {exc}', file_path=dest) from exc
    return CopyDefaultConfigResult(output_path=dest.resolve(), warnings=warnings)
